### ISSUE TITLE
prompt doesn't handle all characters

### ISSUE THREAD

**Issue by stellanhaglund** [karpathy/llama2.c#209]
when I prompt with characters like ö, I get not good as the response.

**Comment by karpathy** [comment]
There might be a problem handling non-ASCII characters in the prompt. I'm not sure how C handles this. Python version uses utf-8 encoding.

**Comment by twobob** [comment]
**Assuming windows** 
The command chcp 65001 is used to change the active console code page to UTF-8 on Windows
you could try opening **cmd** and typing

> **chcp** 
> to get your current codepage  - my default is 437
> if you wish to reset your codepage in the terminal at any time you can then just run **chcp 437** (but your number) to do so.

The following will attempt to automatically grab and restore your current codepage gracefully (see above for any issues) and swap it to utf-8 before you run your command
**for /f "tokens=4" %i in ('chcp') do (chcp 65001 && run.exe ./out/stories44m.bin 0 0 "My utf8 prömpt" && chcp %i)**

no way to test if that is the issue here but that would be the thrust of it.
assuming that was the issue you could elect to either run a term in chcp 65001 or do the kind of switcheroo wangle outlined in the oneliner

Hope it helps

**Comment by richinseattle** [comment]
On Windows, it can be as easy as using `wmain(int argc, char **wchar_t argv)` instead of traditional main to support unicode strings, but that differs from the solution on Linux.

**Comment by atamurad** [comment]
I checked what's going wrong here.

Issue 1: Need to merge multi-byte UTF8 bytes when doing initial str_lookup in bpe_encode.
Smth like this works, not sure if there's a simpler way:
```C
    for (char *c = text; *c != '\0'; c++) {

        // check if char is part of multi-byte UTF8 encoding
        if( (*c & 0xc0) == 0x80) {
            // append it to buffer
            size_t str_len = strlen(str_buffer);
            str_buffer[str_len] = *c;
            str_buffer[str_len+1] = '\0';
        } else {
            sprintf(str_buffer, "%c", *c);
        }

        int id = str_lookup(str_buffer, vocab, vocab_size);

        if(id != -1) {
            tokens[*n_tokens] = id;
            (*n_tokens)++;
        }
    }

```

Issue 2. Byte piece strings in sentencepiece model ("<0x..>") are exported as raw bytes to tokenizer.bin. UTF8 encode at python converts byte to multibyte encoding, and this causes bpe_encode to pick different IDs than sentencepiece. run.c encodes 'ö' as 249, sentencepiece encodes it as 29997.
```ipython
In [33]: chr(0xf6).encode("utf8")
Out[33]: b'\xc3\xb6'

In [34]: chr(0xf6)
Out[34]: 'ö'
```

sentencepiece does `PieceToByte` conversion at decode/output stage. 

I can submit PR later for UTF8 support.
