### ISSUE TITLE
Big speed regression with top-p sampling

### ISSUE THREAD

**Issue by xefoci7612** [karpathy/llama2.c#246]
On my system from 40 tok/s down to 33 tok/s, almost 20% slower...

```
$ ./run /tmp/ramdisk/model110m.bin -s 1 -p 0
Once upon a time <stripped> make a big difference in the world.
achieved tok/s: 40.298507
$ ./run /tmp/ramdisk/model110m.bin -s 1
Once upon a time <stripped> make a big difference in the world.
achieved tok/s: 33.588093
```

Slowdown is even more dramatic on smaller models

**Comment by xefoci7612** [comment]
Sorting all the probabilities seems an overkill.

Picking the top K largest values can be done in O(n) by a [selection algorithm](https://en.wikipedia.org/wiki/Selection_algorithm), like  [std::nth_element](https://en.cppreference.com/w/cpp/algorithm/nth_element) in std library.

Eventually we can keep full sorting but after a top-k step. It could be possible to chain top-K and top-P as described [here](https://huggingface.co/blog/how-to-generate):

`While in theory, Top-p seems more elegant than Top-K, both methods work well in practice. Top-p can also be used in combination with Top-K, which can avoid very low ranked words while allowing for some dynamic selection.
`

For instance a top-K with k=60 before top-p will reduce final sorting from 30K elements of vocab to just 60....with a very high probability of getting the same result of a full sort.

**Comment by twobob** [comment]
./run
Usage:   run <checkpoint> [options]
Example: run model.bin -t 0.9 -n 256 -p "Once upon a time"
Options:
  -t <float>  temperature, default 0.9
  -s <int>    random seed, default time(NULL)
  -n <int>    number of steps to run for, default 256. 0 = max_seq_len
  -p <string> prompt string, default none
  -o <float> top_p, default 1.0
  -k <int> print_tokens, 1 or 0 flag default 1
  -f <int> saveFileBool, 1 or 0 flag default 1
  -l <int> saveLogBool, 1 or 0 flag saves timestamps for tokens gen default 0
  -b <int> singleBOS, 1 or 0 flag default 1
  -d <string> dirname string, default none
  
  qlora\llama2.c> 1..3 | ForEach-Object { 'runmingw.exe', 'rungcc.exe', 'run.exe' | ForEach-Object { $env:OMP_NUM_THREADS=4; & "./$_" '../out/model110M.bin' -t 0 -n 0 -p "Once upon a time" -s 42 -o 1.0 -k 0 -f 0 -l 0 -b 1 -d inbox } }

achieved tok/s: 89.689637 for MINGW
achieved tok/s: 90.555015 for GCC
achieved tok/s: 99.960915 for CLANG

achieved tok/s: 90.555015 for MINGW
achieved tok/s: 90.426942 for GCC
achieved tok/s: 95.162791 for CLANG

achieved tok/s: 90.187781 for MINGW
achieved tok/s: 91.062845 for GCC
achieved tok/s: 101.037037 for CLANG

qlora\llama2.c> 1..3 | ForEach-Object { 'runmingw.exe', 'rungcc.exe', 'run.exe' | ForEach-Object { $env:OMP_NUM_THREADS=4; & "./$_" '../out/model110M.bin' -t 0 -n 0 -p "Once upon a time" -s 42 -o .5 -k 0 -f 0 -l 0 -b 1 -d inbox  } }

achieved tok/s: 88.000000 for MINGW using top_p
achieved tok/s: 89.080460 for GCC using top_p
achieved tok/s: 98.745174 for CLANG using top_p

achieved tok/s: 88.594440 for MINGW using top_p
achieved tok/s: 89.072704 for GCC using top_p
achieved tok/s: 98.745174 for CLANG using top_p

achieved tok/s: 87.879048 for MINGW using top_p
achieved tok/s: 86.372847 for GCC using top_p
achieved tok/s: 87.533156 for CLANG using top_p

Hard to say since being a cpu bound system with so much other overhead but running it with a variety of builds and over a period of time I would probably concur with these findings. fwiw.

**Comment by twobob** [comment]
I ran a bunch more tests, some top p some not and when looking at the logs it did seem to now have two tiers of speed, this my lean into a noticable slowdown when using top _p 
(I have actually shaved many of the other slowdowns from this version of the logging, so an A/B is doable)
![image](https://github.com/karpathy/llama2.c/assets/915232/69de57ba-aceb-4e0b-9c5c-8a0623dfa94d)
I'll add some individualised logging for top_p RSN, was just incidental findings. Far from conclusive
![image](https://github.com/karpathy/llama2.c/assets/915232/3a502cd4-f2e0-43a5-ac70-7f47c7b42d9b)
but yeah. might need some fluffing

**Comment by karpathy** [comment]
I think fixed now ty
