### ISSUE TITLE
clang: error: unsupported option '-fopenmp'

### ISSUE THREAD

**Issue by vgoklani** [karpathy/llama2.c#49]
Curious, I have an Apple M2 Macbook Pro, and I get this error when compiling:

    clang -Ofast -fopenmp -march=native run.c  -lm  -o run

    clang: error: unsupported option '-fopenmp'
    clang: error: unsupported option '-fopenmp'

What's the proper way of setting up OpenMP in Apple land? 

I've already setup homebrew and done this:

     brew install llvm libomp

What should I do next? thanks!

**Comment by Yannlecun** [comment]
Try:
`clang -Ofast -L/opt/homebrew/Cellar/libomp/16.0.6/lib -I/opt/homebrew/Cellar/libomp/16.0.6/include -lomp  run.c -lm -o run`

./run out/model44m.bin

<s>
 Once upon a time, there was a big, thick tree in a park. The tree had many branches and leaves. It was a nice place for kids to play and have fun. One day, a boy named Tim came to the park. He saw the thick tree and thought it would be a good place to protect his toys.
Tim loved to exercise, so he ran around the tree, playing with his toys. He threw his ball, and he jumped. He had so much fun in the thick tree. The tree made him feel happy and safe.
One day, a big storm came and made the ground very rough. The wind blew, and the rain fell. Tim was sad because he could not play outside with his toys. The thick tree had to protect the toys from the wind and rain. The storm did not stop, and Tim's toys were broken. Tim learned that sometimes even when you have fun, bad things can happen.
<s>
 Once upon a time, there was a little girl named Lily. She loved to play outside and explore the world around her. One day, she found a funny looking bug in her yard. It had big eyes and a little antenna on its back. 
achieved tok/s: 1013.861386

**Comment by vgoklani** [comment]
@Yannlecun thank  you :)

**Comment by vgoklani** [comment]
@Yannlecun thank you :)
